# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Database Test

on:
  push:
    branches: [ main, 'develop*' ]
  pull_request:
    branches: [ main ]

jobs:
  test-database:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install SQLite
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3
        sqlite3 --version
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create test database and run migrations
      run: |
        # Set test database path
        echo "DATABASE_URL=file:./test.db" > .env.test
        
        # Generate Prisma client
        npx prisma generate
        
        # Run migrations to create database and schema
        DATABASE_URL=file:./test.db npx prisma migrate deploy

    - name: Seed database with data for testing
      run: |
        # Seed the database with data for testing
        DATABASE_URL=file:./test.db node prisma/seed.js

        - name: Verify database seeding
        run: |
          # Create a simple verification script
          cat > verify-seed.js << 'ENDSCRIPT'
          const { PrismaClient } = require('@prisma/client');
          const prisma = new PrismaClient();
          
          async function verifySeeding() {
            try {
              // Get table information
              const tables = await prisma.$queryRaw`SELECT name FROM sqlite_master WHERE type='table'`;
              console.log('Tables in database:', tables);
              
              // Count recipes
              const recipeCount = await prisma.recipe.count();
              console.log('Recipe count:', recipeCount);
              
              // Count ingredients
              const ingredientCount = await prisma.ingredient.count();
              console.log('Ingredient count:', ingredientCount);
              
              // Look for specific recipe
              const recipe = await prisma.recipe.findFirst({
                where: { name: { contains: 'Chili' } }
              });
              
              if (recipe) {
                console.log('Found recipe:', recipe.name);
                console.log('Verification successful!');
              } else {
                console.log('Could not find expected recipe');
                process.exit(1);
              }
            } catch (error) {
              console.error('Verification error:', error);
              process.exit(1);
            } finally {
              await prisma.$disconnect();
            }
          }
          
          verifySeeding();
          ENDSCRIPT
          
          # Run the verification script with the same DATABASE_URL
          DATABASE_URL=file:./test.db node verify-seed.js